# Hyprtoolkit config
# https://wiki.hypr.land/Hypr-Ecosystem/hyprtoolkit/

background = 0xFF181818
base = 0xFF202020
text = 0xFFDADADA
alternate_base = 0xFF272727
bright_text = 0xFFFFDEDE
accent = 0xFF1A5FB4
accent_secondary = 0xFF0099F0

h1_size = 18
h2_size = 16
h3_size = 14
font_size = 12
small_font_size = 10

icon_theme =
font_family = IBM Plex Sans
font_family_monospace = monospace

rounding_large = 10
rounding_small = 5
