extensions=(
2gua.rainbow-brackets
atlassian.atlascode
chakrounanas.turbo-console-log
christian-kohler.npm-intellisense
dbaeumer.vscode-eslint
dendron.dendron
dendron.dendron-markdown-links
dendron.dendron-markdown-preview-enhanced
dendron.dendron-markdown-shortcuts
dendron.dendron-paste-image
dendron.dendron-snippet-maker
eamodio.gitlens
editorconfig.editorconfig
esbenp.prettier-vscode
firefox-devtools.vscode-firefox-debug
formulahendry.auto-close-tag
formulahendry.auto-rename-tag
hbenl.vscode-mocha-test-adapter
hbenl.vscode-test-explorer
mikestead.dotenv
mongodb.mongodb-vscode
msjsdiag.debugger-for-chrome
msjsdiag.vscode-react-native
ms-vscode.test-adapter-converter
naumovs.color-highlight
pkief.material-icon-theme
planbcoding.vscode-react-refactor
redhat.vscode-yaml
rvest.vs-code-prettier-eslint
sendhil.vscode-file-explorer-menu
srmeyers.git-prefix
steoates.autoimport
streetsidesoftware.code-spell-checker
sysoev.language-stylus
vscodevim.vim
vuhrmeister.vscode-meteor
wix.vscode-import-cost
yatki.vscode-surround
zhuangtongfa.material-theme
)

for extension in ${extensions[@]}; do
  code --install-extension $extension
done
